export const AVAILABLE_CHAINS = [
  {
    chainId: 1,
    litChainId: "ethereum",
    label: "Ethereum",
    symbol: "ETH",
  },
  {
    chainId: 137,
    litChainId: "polygon",
    label: "Polygon",
    symbol: "MATIC",
  },
  {
    chainId: 250,
    litChainId: "fantom",
    label: "Fantom",
    symbol: "FTM",
  },
  {
    chainId: 100,
    litChainId: "xdai",
    label: "Gnosis",
    symbol: "xDAI",
  },
  {
    chainId: 42161,
    litChainId: "arbitrum",
    label: "Arbitrum",
    symbol: "ETH",
  },
  {
    chainId: 43114,
    litChainId: "avalanche",
    label: "Avalanche",
    symbol: "AVAX",
  },
  {
    chainId: 43113,
    litChainId: "fuji",
    label: "Fuji Testnet",
    symbol: "AVAX",
  },
  {
    chainId: 1666600000,
    litChainId: "harmony",
    label: "Harmony",
    symbol: "ONE",
  },
  {
    chainId: 42,
    litChainId: "kovan",
    label: "Kovan Testnet",
    symbol: "ETH",
  },
  {
    chainId: 80001,
    litChainId: "mumbai",
    label: "Mumbai Testnet",
    symbol: "MATIC",
  },
  {
    chainId: 5,
    litChainId: "goerli",
    label: "Goerli Testnet",
    symbol: "ETH",
  },
  {
    chainId: 25,
    litChainId: "cronos",
    label: "Cronos",
    symbol: "CRO",
  },
  {
    chainId: 10,
    litChainId: "optimism",
    label: "Optimism",
    symbol: "ETH",
  },
  {
    chainId: 42220,
    litChainId: "celo",
    label: "Celo",
    symbol: "CELO",
  },
  {
    chainId: 1313161554,
    litChainId: "aurora",
    label: "Aurora",
    symbol: "ETH",
  },
  {
    chainId: 955305,
    litChainId: "eluvio",
    label: "Eluvio",
    symbol: "ELV",
  },
  {
    chainId: 44787,
    litChainId: "alfajores",
    label: "Alfajores Testnet",
    symbol: "CELO",
  },
  {
    chainId: 50,
    litChainId: "xdc",
    label: "XinFin XDC Network",
    symbol: "XDC",
  },
  {
    chainId: 9001,
    litChainId: "evmos",
    label: "Evmos",
    symbol: "EVMOS",
  },
  {
    chainId: 9000,
    litChainId: "evmosTestnet",
    label: "Evmos Testnet",
    symbol: "EVMOS",
  },
];
